import express from 'express';
import { createProxyMiddleware } from 'http-proxy-middleware';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Supabase Proxy (mimics Vite config)
app.use(
  '/api/supabase',
  createProxyMiddleware({
    target: 'https://lcajcnprlvbnqelamqnj.supabase.co',
    changeOrigin: true,
    pathRewrite: { '^/api/supabase': '' },
    on: {
      proxyReq: (proxyReq) => {
        // Usa la clave de entorno si existe, sino usa la tuya
        const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || 'sb_secret_DQsWdev6KYsnSdTbEGK1xw_cJOkkgqk';
        proxyReq.setHeader('apikey', supabaseKey);
        proxyReq.setHeader('Authorization', `Bearer ${supabaseKey}`);
        
        // Remove browser headers
        proxyReq.removeHeader('origin');
        proxyReq.removeHeader('referer');
        proxyReq.setHeader('user-agent', 'node-fetch');
        proxyReq.removeHeader('x-client-info');
        proxyReq.removeHeader('sec-ch-ua');
        proxyReq.removeHeader('sec-ch-ua-mobile');
        proxyReq.removeHeader('sec-ch-ua-platform');
      },
    },
  })
);

// Backblaze Proxy (mimics Vite config)
app.use(
  '/api/b2',
  createProxyMiddleware({
    target: 'https://coopmaza-documentos.s3.us-east-005.backblazeb2.com',
    changeOrigin: true,
    pathRewrite: { '^/api/b2': '' },
  })
);

// Serve static frontend files from 'dist' (generated by `npm run build`)
app.use(express.static(path.join(__dirname, 'dist')));

// Fallback to index.html for React Router
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Servidor de producción corriendo en el puerto ${PORT}`);
});
